In [4]:
import numpy as np

## Given a list of XYZ-coordinates, p,

In [5]:
p = np.array([[1.0, 2.0, 10],
              [3.0, 4.0, 20],
              [5.0, 6.0, 30],
              [7.0, 8.0, 40]])

## Normalise each coordinate by dividing with its Z (3rd) element. For example, the first row becomes:

In [6]:
z = p[:, 2]  
z = z.reshape(-1, 1)
normalized_p = p / z 
print(normalized_p)

[[0.1        0.2        1.        ]
 [0.15       0.2        1.        ]
 [0.16666667 0.2        1.        ]
 [0.175      0.2        1.        ]]


## Create a 3x3 ndarray. Use fancy indexing to slice out the diagonal elements.

In [7]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
diagonal = arr[[0, 1, 2], [0, 1, 2]]

In [8]:
print(diagonal)

[1 5 9]


###  Generate a 10 x 3 array of random numbers (all between 0 and 1). From each row, pick the number closest to 0.75. Make use of np.abs and np.argmax to find the column j which contains the closest element in each row.

In [9]:
arr = np.random.rand(10, 3)
j = np.abs(arr - 0.75).argmin(axis=1)
closest_elements = arr[np.arange(10), j]

In [10]:
closest_elements

array([0.5406553 , 0.91248814, 0.27676267, 0.71602512, 0.93754984,
       0.54251333, 0.73226902, 0.69994428, 0.82882035, 0.84045871])

### predict and verify the shape of the following slicing operation.

In [11]:
x = np.empty((10, 8, 6))

idx0 = np.zeros((3, 8)).astype(int)
idx1 = np.zeros((3, 1)).astype(int)
idx2 = np.zeros((1, 1)).astype(int)

x[idx0, idx1, idx2]

array([[4.0474e-320, 4.0474e-320, 4.0474e-320, 4.0474e-320, 4.0474e-320,
        4.0474e-320, 4.0474e-320, 4.0474e-320],
       [4.0474e-320, 4.0474e-320, 4.0474e-320, 4.0474e-320, 4.0474e-320,
        4.0474e-320, 4.0474e-320, 4.0474e-320],
       [4.0474e-320, 4.0474e-320, 4.0474e-320, 4.0474e-320, 4.0474e-320,
        4.0474e-320, 4.0474e-320, 4.0474e-320]])