In [14]:
import numpy as np

## Create a null vector of size 10 but the fifth value which is 1

In [15]:
null_vector = np.zeros(10)
null_vector[4] = 1

## Create a vector with values ranging from 10 to 49

In [16]:
my_vector = np.arange(10, 50)

## Reverse a vector (first element becomes last)


In [17]:
 my_vector[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

##  Create a 3x3 matrix with values ranging from 0 to 8

In [18]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Find indices of non-zero elements from [1,2,0,0,4,0]

In [19]:
np.nonzero((np.array([1, 2, 0, 0, 4, 0])))

(array([0, 1, 4]),)

## Create a random vector of size 30 and find the mean value

In [20]:
my_vector = np.random.rand(30)
np.mean(my_vector)

0.5273727216441876

## Create a 2d array with 1 on the border and 0 inside

In [21]:
my_matrix = np.ones((5, 5))
my_matrix[1:-1, 1:-1] = 0

## Create a 8x8 matrix and fill it with a checkerboard pattern


In [23]:
my_matrix = np.zeros((8, 8))
my_matrix[::2, ::2] = 1
my_matrix[1::2, 1::2] = 1

In [24]:
my_matrix

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

## Create a checkerboard 8x8 matrix using the tile function

In [25]:
checkerboard = np.array([[0, 1], [1, 0]])
my_matrix = np.tile(checkerboard, (4, 4))
my_matrix

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## Given a 1D array, negate all elements which are between 3 and 8, in place


In [27]:
Z = np.arange(11)

# Find the indices of elements between 3 and 8
idx = np.where((Z >= 3) & (Z <= 8))

# Negate the elements between 3 and 8 in-place
Z[idx] = -Z[idx]
Z

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10])

## Create a random vector of size 10 Z = np.random.random(10) and sort it

In [28]:
Z = np.random.random(10)
Z.sort()

## Consider two random array A anb B, check if they are equal

In [29]:
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)

print(A)
print(B)

if np.array_equal(A, B):
    print("Arrays A and B are equal")
else:
    print("Arrays A and B are not equal")

[0 0 0 0 0]
[1 1 1 1 0]
Arrays A and B are not equal


## How to convert an integer (32 bits) array into a float (32 bits) in place?

In [30]:

Z = np.arange(10, dtype=np.int32)

Z = Z.view(np.float32)
Z[:] = Z.astype(np.float32)

print(Z)

[0.0e+00 1.4e-45 2.8e-45 4.2e-45 5.6e-45 7.0e-45 8.4e-45 9.8e-45 1.1e-44
 1.3e-44]


## How to get the diagonal of a dot product?

In [31]:
A = np.arange(9).reshape(3,3)
B = A + 1
C = np.dot(A, B)
D = np.diagonal(C)

print(D)

[ 18  66 132]
