In [1]:
import numpy as np

In [2]:
from scipy import linalg

In [123]:
A = np.array([[3, 2, 0], [1, -1, 0], [0, 5, 1]])

In [124]:
A

array([[ 3,  2,  0],
       [ 1, -1,  0],
       [ 0,  5,  1]])

In [84]:
b = np.array([1,2,3],dtype="float")

In [125]:
x = np.linalg.solve(A, b)

In [126]:
np.dot(A, x) == b

array([ True,  True,  True])

In [127]:
D = np.random.sample(9).reshape((3,3))

In [128]:
D

array([[0.47892504, 0.95324321, 0.60069176],
       [0.37222148, 0.84868673, 0.33792217],
       [0.22522762, 0.72574783, 0.06280151]])

In [132]:
x2 = np.linalg.solve(a, D)

In [133]:
x2

array([[ 0.2446736 ,  0.53012333,  0.25530722],
       [-0.12754788, -0.3185634 , -0.08261495],
       [ 0.86296703,  2.31856481,  0.47587626]])

In [134]:
np.dot(a,x2) == D

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [136]:
A

array([[ 3,  2,  0],
       [ 1, -1,  0],
       [ 0,  5,  1]])

In [139]:
eigenvalues, eigenvectors = linalg.eig(A)

In [140]:
eigenvalues

array([ 1.        +0.j, -1.44948974+0.j,  3.44948974+0.j])

In [141]:
eigenvectors

array([[ 0.        ,  0.19399248, -0.89052821],
       [ 0.        , -0.43158379, -0.20014165],
       [ 1.        ,  0.88096671, -0.40853743]])

In [143]:
linalg.inv(A)

array([[ 0.2,  0.4,  0. ],
       [ 0.2, -0.6,  0. ],
       [-1. ,  3. ,  1. ]])

In [145]:
linalg.det(A)

-5.0

In [149]:
linalg.norm(A)

6.4031242374328485

In [151]:
linalg.norm(A,ord='fro')

6.4031242374328485

In [153]:
linalg.norm(A,ord=np.inf)

6.0

In [154]:
linalg.norm(A,ord=-np.inf)

2.0

In [155]:
linalg.norm(A,ord='nuc')

8.941887662749203